# set Java
ARG JAVA_VERSION=17
# extracts spring layers from the app jar (to optimize boot)
FROM eclipse-temurin:${JAVA_VERSION}-jre as build

ARG HAWKBIT_APP=hawkbit-update-server
ARG HAWKBIT_VERSION=pass_as_buils_arg


ENV BUILD_DIR=/opt/hawkbit_build
ENV APP=${HAWKBIT_APP}
ENV VERSION=${HAWKBIT_VERSION}
ARG MARIADB_DRIVER_VERSION=3.1.4
ENV MARIADB_DRIVER_VERSION=${MARIADB_DRIVER_VERSION}

COPY KEY .

RUN set -x &&\
 apt-get update &&\
 apt-get install -y --no-install-recommends gnupg unzip wget &&\
 gpg --import KEY &&\
 mkdir -p ${BUILD_DIR} &&\
 cd ${BUILD_DIR} &&\
 wget -O ${APP}.jar --no-verbose https://repo1.maven.org/maven2/org/eclipse/hawkbit/${APP}/${VERSION}/${APP}-${VERSION}.jar &&\
 wget -O ${APP}.jar.asc --no-verbose https://repo1.maven.org/maven2/org/eclipse/hawkbit/${APP}/${VERSION}/${APP}-${VERSION}.jar.asc &&\
 gpg --batch --verify ${APP}.jar.asc ${APP}.jar &&\
 java -Djarmode=layertools -jar ${APP}.jar extract --destination . &&\
 rm ${APP}.jar ${APP}.jar.asc /KEY

COPY KEY-mysql .

RUN set -x &&\
 gpg --import KEY-mysql &&\
 wget -O ${BUILD_DIR}/mariadb-java-client-${MARIADB_DRIVER_VERSION}.jar --no-verbose https://downloads.mariadb.com/Connectors/java/connector-java-3.1.4/mariadb-java-client-3.1.4.jar &&\
 wget -O ${BUILD_DIR}/mariadb-java-client-${MARIADB_DRIVER_VERSION}.jar.asc --no-verbose https://downloads.mariadb.com/Connectors/java/connector-java-3.1.4/mariadb-java-client-3.1.4.jar.asc &&\
 gpg --verify --batch ${BUILD_DIR}/mariadb-java-client-${MARIADB_DRIVER_VERSION}.jar.asc ${BUILD_DIR}/mariadb-java-client-${MARIADB_DRIVER_VERSION}.jar &&\
 apt-get remove -y gnupg unzip wget &&\
 apt-get autoremove -y &&\
 rm -rf /var/lib/apt/lists/* &&\
 ls -la ${BUILD_DIR}/ &&\
 rm ${BUILD_DIR}/mariadb-java-client-${MARIADB_DRIVER_VERSION}.jar.asc /KEY-mysql


FROM eclipse-temurin:${JAVA_VERSION}-jre
RUN groupadd hawkbit_group && useradd -ms /bin/bash -g hawkbit_group hawkbit
RUN mkdir -p /artifactrepo && chown -R hawkbit /artifactrepo
USER hawkbit

ENV BUILD_DIR=/opt/hawkbit_build
COPY --from=build ${BUILD_DIR}/dependencies/ ./
RUN true
COPY --from=build ${BUILD_DIR}/spring-boot-loader/ ./
RUN true
COPY --from=build ${BUILD_DIR}/snapshot-dependencies/ ./
RUN true
COPY --from=build ${BUILD_DIR}/application/ ./
RUN true
ARG MARIADB_DRIVER_VERSION=3.1.4
COPY --from=build ${BUILD_DIR}/mariadb-java-client-${MARIADB_DRIVER_VERSION}.jar ./BOOT-INF/lib/
RUN true
ARG CONTAINER_PORT=8080
ENV JAVA_OPTS="-Dspring.profiles.active=mysql -Xms768m -Xmx768m -XX:MaxMetaspaceSize=250m -XX:MetaspaceSize=250m -Xss300K -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError"

VOLUME "/artifactrepo"
EXPOSE ${CONTAINER_PORT}
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} org.springframework.boot.loader.JarLauncher ${@}"]